### PR TITLE
Add WSL XServer Instructions, solves issue #22

### PR DESCRIPTION
**Pull request by callumhauber**

### CODE REVIEW

**Comment by johnnyapol** [comment]
It's probably worth reviewing https://docs.microsoft.com/en-us/windows/wsl/tutorials/gui-apps - for people on a new enough Windows, there's native support for GUI apps. That should probably be the primary advice and then this as a backup.

**Comment by callumhauber** [comment]
I didn't realize that existed, thanks! Pretty funny that article didn't come up when I was trying to make things work earlier.

**Comment by jina2k** [comment]
I found it easier to just download Git in general instead of doing this. I still had issues for some reason and will probably revisit later if need be. https://git-scm.com/downloads

**Comment by jina2k** [comment]
Revisited the issue, turns out after following a comment from a user about enabling for public and private networks made it work. My habit of just enabling private networks wasn't working for me as I was connected to a public network.

**Pull request merged**
